/**
 * Customer Success Agent — Wave 2
 *
 * Sends proactive weekly success-nudge emails to customers. The agent:
 *   1. Honours `brand_fingerprints.requires_human_approval`: if true, the nudge
 *      is queued into `approval_queue` instead of being sent.
 *   2. Hard-gates YMYL content: if a YMYL keyword is detected anywhere in the
 *      nudge context OR draft, the email is NEVER sent automatically — it is
 *      routed to `approval_queue` with `evidence.ymyl=true`.
 *   3. Sends via Resend using the `success-nudge` template (brand-tone-aware
 *      copy generated by Sonnet 4.6).
 *   4. Logs an `audit_log` row on every external action (send OR defer).
 *   5. Emits a `cost.alert` event when the per-customer weekly cost exceeds
 *      $0.50, and refuses to run if the per-run cost would exceed $1.00.
 *
 * Triggers (consumed by Inngest functions — NOT created here):
 *   - cron `customer.success.weekly` — Sundays 14:00 customer local
 *   - event `approval.rejected`
 *   - event `deliverables.over_cap`
 *
 * Architecture per CLAUDE.md:
 *   - Direct Anthropic SDK (NOT Vercel AI SDK)
 *   - Sonnet 4.6 (`claude-sonnet-4-6`)
 *   - Stable system prompt cached with `cache_control: ephemeral`
 *   - Voice Canon Model B — never names the agent in customer-facing copy
 *
 * Group A integration (deliverables-gate) — see TODO at the bottom of
 * `runCustomerSuccessNudge`. If `lib/billing/deliverables.ts` arrives, wire
 * `consumeDeliverable` BEFORE the email send.
 */

import Anthropic from '@anthropic-ai/sdk';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { randomUUID } from 'crypto';
import * as React from 'react';
import { sendEmail } from '../../email/client';
import { SuccessNudgeEmail } from '../../../emails/success-nudge';
import { detectYmyl, type YmylMatch } from '../shared/ymyl';
import { logAudit, type AuditClient } from '../shared/audit';
import { buildSuccessNudgeSystemPrompt, buildSuccessNudgeUserPrompt } from './prompt';

// ---------------------------------------------------------------------------
// Config — Sonnet 4.6 + per-run/weekly cost ceilings
// ---------------------------------------------------------------------------
const MODEL = 'claude-sonnet-4-6';

// Sonnet 4.6 pricing (per CLAUDE.md models map, May 2026 locked).
const COST_PER_1M_INPUT = 3.0;
const COST_PER_1M_OUTPUT = 15.0;
const COST_PER_1M_CACHE_READ = 0.3; // ~10% of input

/** Hard ceiling — refuse to send if a single run costs more than this. */
export const RUN_COST_CEILING_USD = 1.0;
/** Alert threshold — emit `cost.alert` when per-customer-per-week exceeds this. */
export const WEEKLY_COST_ALERT_THRESHOLD_USD = 0.5;

/** Trigger reason — drives whether the nudge focuses on momentum (cron) or recovery (event). */
export type NudgeTrigger =
  | 'cron_weekly'
  | 'approval_rejected'
  | 'deliverables_over_cap';

// ---------------------------------------------------------------------------
// Public input/output types
// ---------------------------------------------------------------------------
export interface CustomerSuccessInput {
  customerId: string;
  customerEmail: string;
  firstName: string;
  businessName: string;
  trigger: NudgeTrigger;
  /** Last-week summary: brief, bullet-style facts the LLM uses to draft. */
  weeklyContext: {
    /** Visibility deltas, fresh content, scan improvements, etc. */
    wins: string[];
    /** Items that are queued or running. */
    queued: string[];
    /** Any concerns the agent must address (e.g. rejection reason). */
    concerns?: string[];
  };
  /**
   * From `brand_fingerprints.requires_human_approval`. When true the nudge
   * is queued into `approval_queue` and NOT sent automatically.
   */
  requiresHumanApproval: boolean;
  /** brief_version_id from brand_fingerprints — required for traceability. */
  briefVersionId: string;
  /**
   * Brand voice tone descriptors — passed to the LLM as the only voice guide.
   * Pulled from `brand_fingerprints.voice.tone_descriptors`.
   */
  toneDescriptors: string[];
  /** Optional dashboard CTA. */
  ctaUrl?: string;
}

export type CustomerSuccessOutcome =
  | {
      kind: 'sent';
      messageId: string;
      costUsd: number;
      draft: NudgeDraft;
    }
  | {
      kind: 'deferred_approval';
      approvalQueueId: string;
      reason: 'requires_human_approval' | 'ymyl' | 'first_50_customers';
      costUsd: number;
      draft: NudgeDraft;
    }
  | {
      kind: 'aborted';
      reason: 'cost_ceiling' | 'llm_error' | 'draft_invalid';
      costUsd: number;
    };

/** Structured draft the LLM returns. */
export interface NudgeDraft {
  subject: string;
  highlights: string[];
  comingUp: string[];
  /** Free-form intro line, optional. */
  intro?: string;
}

// ---------------------------------------------------------------------------
// Cost helpers
// ---------------------------------------------------------------------------

/** Per-call USD cost given Anthropic usage. */
export function computeCostUsd(
  inputTokens: number,
  outputTokens: number,
  cacheReadTokens: number,
): number {
  return (
    (inputTokens / 1_000_000) * COST_PER_1M_INPUT +
    (outputTokens / 1_000_000) * COST_PER_1M_OUTPUT +
    (cacheReadTokens / 1_000_000) * COST_PER_1M_CACHE_READ
  );
}

// ---------------------------------------------------------------------------
// Supabase admin client — only constructed when we actually need DB access
// ---------------------------------------------------------------------------
function getAdminClient(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error(
      '[customer-success] Supabase env vars not configured (NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY)',
    );
  }
  return createClient(url, key, { auth: { persistSession: false } });
}

// ---------------------------------------------------------------------------
// Anthropic client (overridable for tests)
// ---------------------------------------------------------------------------
export interface AnthropicLike {
  messages: {
    create: (params: Anthropic.MessageCreateParamsNonStreaming) => Promise<Anthropic.Message>;
  };
}

function defaultAnthropic(): AnthropicLike {
  return new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
}

// ---------------------------------------------------------------------------
// Draft parsing
// ---------------------------------------------------------------------------

function parseDraft(raw: string): NudgeDraft | null {
  // Strip markdown fences in case the model wraps despite the instruction.
  const cleaned = raw
    .replace(/^```json\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null) return null;
  const obj = parsed as Record<string, unknown>;
  const subject = typeof obj.subject === 'string' ? obj.subject : null;
  const highlights = Array.isArray(obj.highlights)
    ? obj.highlights.filter((x): x is string => typeof x === 'string')
    : null;
  const comingUp = Array.isArray(obj.coming_up)
    ? obj.coming_up.filter((x): x is string => typeof x === 'string')
    : null;
  if (!subject || !highlights || !comingUp) return null;
  if (subject.length === 0 || subject.length > 120) return null;
  return {
    subject,
    highlights,
    comingUp,
    intro: typeof obj.intro === 'string' ? obj.intro : undefined,
  };
}

// ---------------------------------------------------------------------------
// approval_queue insert
// ---------------------------------------------------------------------------

interface ApprovalQueueInsertParams {
  customerId: string;
  draft: NudgeDraft;
  trigger: NudgeTrigger;
  ymyl: YmylMatch | null;
  briefVersionId: string;
  reason: 'requires_human_approval' | 'ymyl' | 'first_50_customers';
  client: SupabaseClient;
}

async function insertApprovalQueueRow(
  params: ApprovalQueueInsertParams,
): Promise<string> {
  const approvalToken = randomUUID();
  const evidence = {
    draft: params.draft,
    provenance: {
      source_event: params.trigger,
      brief_version_id: params.briefVersionId,
      generated_by: 'customer_success_agent',
    },
    risk_flags: params.ymyl ? ['ymyl'] : [],
    ymyl: params.ymyl ? { matched: params.ymyl.pattern, reason: params.ymyl.reason } : null,
    defer_reason: params.reason,
  };
  // Per migration 20260525000001 the `approval_kind` enum does not include 'ymyl'.
  // We route everything from the success agent as `email_as_them` (the Resend
  // payload IS an email "as" the customer-success voice) and surface YMYL via
  // `evidence.risk_flags`. Schema-level YMYL gating is enforced by the
  // approval queue UI + the audit_log entry below.
  const row = {
    customer_id: params.customerId,
    kind: 'email_as_them' as const,
    state: 'pending' as const,
    resource: {
      kind: 'success_nudge_email',
      subject: params.draft.subject,
      highlights: params.draft.highlights,
      coming_up: params.draft.comingUp,
    },
    evidence,
    approval_token: approvalToken,
  };
  const { data, error } = await params.client
    .from('approval_queue')
    .insert(row)
    .select('id')
    .single();
  if (error) {
    throw new Error(`[customer-success] approval_queue insert failed: ${error.message}`);
  }
  const id = (data as { id?: string } | null)?.id;
  if (!id) {
    throw new Error('[customer-success] approval_queue insert returned no id');
  }
  return id;
}

// ---------------------------------------------------------------------------
// Main entry — runCustomerSuccessNudge
// ---------------------------------------------------------------------------

export interface RunCustomerSuccessNudgeDeps {
  /** Defaults to a new Anthropic client backed by `ANTHROPIC_API_KEY`. */
  anthropic?: AnthropicLike;
  /** Defaults to the Resend-backed `sendEmail` in `lib/email/client`. */
  sendEmail?: typeof sendEmail;
  /** Defaults to the Supabase service-role client. */
  supabase?: SupabaseClient;
  /** Audit log writer — defaults to `logAudit` against the Supabase client. */
  auditClient?: AuditClient;
  /**
   * Cost-alert emitter — receives one call when the per-run cost exceeds
   * `WEEKLY_COST_ALERT_THRESHOLD_USD`. Defaults to `console.warn`-only; the
   * Inngest function should wrap this with `inngest.send({ name: 'cost.alert' })`.
   */
  emitCostAlert?: (payload: {
    customerId: string;
    feature: 'customer_success';
    costUsd: number;
  }) => Promise<void> | void;
}

/**
 * Run one nudge for one customer. Returns the outcome — the caller (an
 * Inngest function) is responsible for retries, scheduling, and event fan-out.
 */
export async function runCustomerSuccessNudge(
  input: CustomerSuccessInput,
  deps: RunCustomerSuccessNudgeDeps = {},
): Promise<CustomerSuccessOutcome> {
  const anthropic = deps.anthropic ?? defaultAnthropic();
  const supabase = deps.supabase ?? getAdminClient();
  // Supabase's `.from().insert()` is awaitable at runtime even though its type
  // is PostgrestFilterBuilder rather than Promise. Cast through unknown to
  // satisfy the minimal AuditClient surface.
  const auditClient: AuditClient =
    deps.auditClient ?? ({ from: supabase.from.bind(supabase) } as unknown as AuditClient);
  const sender = deps.sendEmail ?? sendEmail;
  const emitCostAlert = deps.emitCostAlert;

  const sessionId = randomUUID();
  const systemPrompt = buildSuccessNudgeSystemPrompt();
  const userPrompt = buildSuccessNudgeUserPrompt({
    firstName: input.firstName,
    businessName: input.businessName,
    trigger: input.trigger,
    weeklyContext: input.weeklyContext,
    toneDescriptors: input.toneDescriptors,
  });

  // -------------------------------------------------------------------------
  // 1. Up-front YMYL check on inbound context — if the trigger payload
  //    references medical/legal/financial content the nudge is hard-gated
  //    even before the LLM runs (defence-in-depth).
  // -------------------------------------------------------------------------
  const inboundCorpus = [
    ...input.weeklyContext.wins,
    ...input.weeklyContext.queued,
    ...(input.weeklyContext.concerns ?? []),
  ].join('\n');
  const inboundYmyl = detectYmyl(inboundCorpus);

  // -------------------------------------------------------------------------
  // 2. LLM call — single non-streaming Anthropic message with cache_control
  // -------------------------------------------------------------------------
  let llm: Anthropic.Message;
  try {
    llm = await anthropic.messages.create({
      model: MODEL,
      max_tokens: 800,
      temperature: 0.3,
      system: [
        {
          type: 'text',
          text: systemPrompt,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: [{ role: 'user', content: userPrompt }],
    });
  } catch (err: unknown) {
    const error = err as { status?: number; message?: string };
    console.error(
      JSON.stringify({
        event: 'llm_error',
        feature: 'customer_success',
        session_id: sessionId,
        customer_id: input.customerId,
        status: error.status ?? null,
        message: error.message ?? 'unknown',
      }),
    );
    if (error.status === 429) {
      throw new Error(
        `[customer-success] LLM rate limit — retry with backoff: ${error.message ?? 'unknown'}`,
      );
    }
    if (error.status === 529) {
      throw new Error(
        `[customer-success] LLM overload — fail gracefully: ${error.message ?? 'unknown'}`,
      );
    }
    return { kind: 'aborted', reason: 'llm_error', costUsd: 0 };
  }

  // -------------------------------------------------------------------------
  // 3. Cost log + per-run ceiling check
  // -------------------------------------------------------------------------
  const inputTokens = llm.usage.input_tokens;
  const outputTokens = llm.usage.output_tokens;
  const cacheReadTokens =
    (llm.usage as { cache_read_input_tokens?: number }).cache_read_input_tokens ?? 0;
  const costUsd = computeCostUsd(inputTokens, outputTokens, cacheReadTokens);

  console.log(
    JSON.stringify({
      event: 'llm_call',
      model: MODEL,
      feature: 'customer_success',
      session_id: sessionId,
      customer_id: input.customerId,
      trigger: input.trigger,
      input_tokens: inputTokens,
      output_tokens: outputTokens,
      cache_read_tokens: cacheReadTokens,
      cost_usd: costUsd,
    }),
  );

  if (costUsd > RUN_COST_CEILING_USD) {
    console.error(
      JSON.stringify({
        event: 'cost_ceiling_exceeded',
        feature: 'customer_success',
        customer_id: input.customerId,
        cost_usd: costUsd,
        ceiling: RUN_COST_CEILING_USD,
      }),
    );
    await logAudit(auditClient, {
      actor_type: 'agent',
      event_type: 'customer_success.aborted_cost_ceiling',
      target_id: input.customerId,
      target_table: 'user_profiles',
      payload: { cost_usd: costUsd, ceiling: RUN_COST_CEILING_USD, trigger: input.trigger },
    });
    return { kind: 'aborted', reason: 'cost_ceiling', costUsd };
  }

  if (costUsd > WEEKLY_COST_ALERT_THRESHOLD_USD && emitCostAlert) {
    await emitCostAlert({
      customerId: input.customerId,
      feature: 'customer_success',
      costUsd,
    });
  }

  // -------------------------------------------------------------------------
  // 4. Parse the draft
  // -------------------------------------------------------------------------
  const block = llm.content[0];
  if (!block || block.type !== 'text') {
    return { kind: 'aborted', reason: 'draft_invalid', costUsd };
  }
  const draft = parseDraft(block.text);
  if (!draft) {
    return { kind: 'aborted', reason: 'draft_invalid', costUsd };
  }

  // -------------------------------------------------------------------------
  // 5. YMYL post-generation check — also scan the produced draft
  // -------------------------------------------------------------------------
  const draftCorpus = [draft.subject, draft.intro ?? '', ...draft.highlights, ...draft.comingUp].join(
    '\n',
  );
  const draftYmyl = detectYmyl(draftCorpus);
  const ymyl = inboundYmyl ?? draftYmyl;

  // -------------------------------------------------------------------------
  // 6. Routing decision — DEFER on YMYL OR brand-fingerprint flag.
  //    Group A integration: deliverables gate. NOT yet wired — see TODO below.
  // -------------------------------------------------------------------------
  const deferReason: 'ymyl' | 'requires_human_approval' | null = ymyl
    ? 'ymyl'
    : input.requiresHumanApproval
      ? 'requires_human_approval'
      : null;

  if (deferReason) {
    const approvalQueueId = await insertApprovalQueueRow({
      customerId: input.customerId,
      draft,
      trigger: input.trigger,
      ymyl,
      briefVersionId: input.briefVersionId,
      reason: deferReason,
      client: supabase,
    });
    await logAudit(auditClient, {
      actor_type: 'agent',
      event_type:
        deferReason === 'ymyl'
          ? 'customer_success.ymyl_deferred'
          : 'customer_success.approval_deferred',
      target_id: approvalQueueId,
      target_table: 'approval_queue',
      payload: {
        customer_id: input.customerId,
        trigger: input.trigger,
        cost_usd: costUsd,
        ymyl_reason: ymyl?.reason ?? null,
        brief_version_id: input.briefVersionId,
      },
    });
    return { kind: 'deferred_approval', approvalQueueId, reason: deferReason, costUsd, draft };
  }

  // -------------------------------------------------------------------------
  // 7. TODO (Group A) — deliverables consumption gate.
  //    When `apps/web/src/lib/billing/deliverables.ts` lands, import
  //    `consumeDeliverable` and call it here:
  //
  //      const ok = await consumeDeliverable({
  //        customerId: input.customerId,
  //        kind: 'outreach_email',
  //      });
  //      if (!ok) {
  //        // emit deliverables.over_cap event + audit_log defer
  //        return { kind: 'aborted', reason: 'deliverables_cap', costUsd };
  //      }
  //
  //    Until Group A ships we proceed unconditionally — sends are gated by
  //    Inngest cron scheduling instead. Tracked in CEO Wave 2 brief.
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // 8. Send via Resend
  // -------------------------------------------------------------------------
  const result = await sender({
    to: input.customerEmail,
    subject: draft.subject,
    react: React.createElement(SuccessNudgeEmail, {
      firstName: input.firstName,
      businessName: input.businessName,
      highlights: draft.highlights,
      comingUp: draft.comingUp,
      ctaUrl: input.ctaUrl,
    }),
    text: buildPlaintext(input, draft),
  });

  if (!result.ok) {
    await logAudit(auditClient, {
      actor_type: 'agent',
      event_type: 'customer_success.send_failed',
      target_id: input.customerId,
      target_table: 'user_profiles',
      payload: {
        trigger: input.trigger,
        error: result.error,
        cost_usd: costUsd,
        brief_version_id: input.briefVersionId,
      },
    });
    return { kind: 'aborted', reason: 'llm_error', costUsd };
  }

  await logAudit(auditClient, {
    actor_type: 'agent',
    event_type: 'customer_success.nudge_sent',
    target_id: input.customerId,
    target_table: 'user_profiles',
    payload: {
      trigger: input.trigger,
      message_id: result.messageId,
      cost_usd: costUsd,
      brief_version_id: input.briefVersionId,
      subject: draft.subject,
    },
  });

  return { kind: 'sent', messageId: result.messageId, costUsd, draft };
}

// ---------------------------------------------------------------------------
// Plaintext fallback for the email
// ---------------------------------------------------------------------------
function buildPlaintext(input: CustomerSuccessInput, draft: NudgeDraft): string {
  const lines: string[] = [];
  lines.push(`${input.firstName}, here's where ${input.businessName} stands this week.`);
  if (draft.intro) lines.push('', draft.intro);
  if (draft.highlights.length > 0) {
    lines.push('', 'This past week:');
    for (const line of draft.highlights) lines.push(`- ${line}`);
  }
  if (draft.comingUp.length > 0) {
    lines.push('', 'Coming up:');
    for (const line of draft.comingUp) lines.push(`- ${line}`);
  }
  lines.push('', '— Beamix');
  return lines.join('\n');
}
