-- Migration: 20260602000001_approval_queue_agent_job_id.sql
-- Purpose: Add agent_job_id column to approval_queue, FK → agent_jobs(id),
--          and a plain UNIQUE index enforcing exactly-one approval row per
--          agent job — DB-layer idempotency backstop for Inngest retry of
--          gated_publish.requested.
--
-- Rollback: see rollback/20260602000001_approval_queue_agent_job_id.rollback.sql
--
-- Notes:
--   - Plain SQL only — no plpgsql DECLARE blocks (memory: feedback_supabase_plpgsql)
--   - agent_job_id is net-new: ALL existing rows are NULL → no dedup/backfill needed
--   - ADD COLUMN IF NOT EXISTS + CREATE UNIQUE INDEX IF NOT EXISTS are idempotent
--   - FK uses DROP CONSTRAINT IF EXISTS + ADD CONSTRAINT for full idempotency
--     (PG has no ADD CONSTRAINT IF NOT EXISTS; drop-then-add is safe and plain SQL)
--   - No RLS change required: this column is an internal FK with no new access surface
--   - ON DELETE SET NULL: deleting an agent_job must not cascade-delete approval history

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add agent_job_id column (nullable — non-agent approvals stay NULL)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.approval_queue
  ADD COLUMN IF NOT EXISTS agent_job_id uuid;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. FK → agent_jobs(id) ON DELETE SET NULL
--    Deleting an agent_job row must not cascade-delete the approval audit trail.
--    Drop-then-add pattern makes the FK step idempotent (safe for CI resets and
--    staging refresh runs) without a plpgsql DO-block.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.approval_queue
  DROP CONSTRAINT IF EXISTS fk_approval_queue_agent_job;

ALTER TABLE public.approval_queue
  ADD CONSTRAINT fk_approval_queue_agent_job
  FOREIGN KEY (agent_job_id) REFERENCES public.agent_jobs(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Plain UNIQUE index — idempotency backstop + ON CONFLICT arbiter
--    Plain unique index (no WHERE predicate): Postgres treats NULLs as DISTINCT
--    by default (NULLS DISTINCT), so multiple NULL agent_job_id rows
--    (non-agent approvals: outreach, digest, etc.) are still allowed — same
--    deduplication semantics as the prior partial index, but a plain unique
--    index IS a valid ON CONFLICT inference target (partial indexes are not),
--    so `ON CONFLICT (agent_job_id) DO NOTHING` works without SQLSTATE 42P10.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS uq_approval_queue_agent_job_id
  ON public.approval_queue (agent_job_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Column comment
-- ─────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.approval_queue.agent_job_id IS
  'FK to agent_jobs.id when the approval was generated by an agent pipeline. '
  'NULL for non-agent-sourced approvals (outreach, digest, etc.). '
  'Plain UNIQUE index uq_approval_queue_agent_job_id (NULLS DISTINCT) enforces '
  'exactly-one approval row per agent job and is a valid ON CONFLICT arbiter — '
  'DB backstop for Inngest retry of gated_publish.requested.';
