-- Migration: 20260602000001_approval_queue_agent_job_id.sql
-- Purpose: Add agent_job_id column to approval_queue, FK → agent_jobs(id),
--          and a partial UNIQUE index enforcing exactly-one approval row per
--          agent job — DB-layer idempotency backstop for Inngest retry of
--          gated_publish.requested.
--
-- Rollback: see rollback/20260602000001_approval_queue_agent_job_id.rollback.sql
--
-- Notes:
--   - Plain SQL only — no plpgsql DECLARE blocks (memory: feedback_supabase_plpgsql)
--   - agent_job_id is net-new: ALL existing rows are NULL → no dedup/backfill needed
--   - ADD COLUMN IF NOT EXISTS + CREATE UNIQUE INDEX IF NOT EXISTS are idempotent
--   - ADD CONSTRAINT is one-shot (no IF NOT EXISTS in PG for named constraints);
--     consistent with repo convention — re-run only if column was added but FK was not
--   - No RLS change required: this column is an internal FK with no new access surface
--   - ON DELETE SET NULL: deleting an agent_job must not cascade-delete approval history

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add agent_job_id column (nullable — non-agent approvals stay NULL)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.approval_queue
  ADD COLUMN IF NOT EXISTS agent_job_id uuid;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. FK → agent_jobs(id) ON DELETE SET NULL
--    Deleting an agent_job row must not cascade-delete the approval audit trail.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.approval_queue
  ADD CONSTRAINT fk_approval_queue_agent_job
  FOREIGN KEY (agent_job_id) REFERENCES public.agent_jobs(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Partial UNIQUE index — idempotency backstop
--    Allows multiple NULLs (non-agent approvals: outreach, digest, etc.).
--    Enforces exactly-one approval row per agent job (deduplication on retry).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS uq_approval_queue_agent_job_id
  ON public.approval_queue (agent_job_id)
  WHERE agent_job_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Column comment
-- ─────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.approval_queue.agent_job_id IS
  'FK to agent_jobs.id when the approval was generated by an agent pipeline. '
  'NULL for non-agent-sourced approvals (outreach, digest, etc.). '
  'Partial UNIQUE index uq_approval_queue_agent_job_id enforces exactly-one '
  'approval row per agent job — DB backstop for Inngest retry of gated_publish.requested.';
