'use client'

import { useState } from 'react'
import {
  FileText,
  BookOpen,
  Code2,
  Star,
  Heart,
  Search,
  BarChart3,
  MessageSquare,
  Share2,
} from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { formatDistanceToNow } from 'date-fns'

const CONTENT_TYPE_META: Record<string, { label: string; icon: React.ComponentType<{ className?: string }>; color: string }> = {
  blog_post: { label: 'Blog Post', icon: BookOpen, color: 'bg-blue-100 text-blue-700' },
  article: { label: 'Article', icon: FileText, color: 'bg-cyan-100 text-cyan-700' },
  faq: { label: 'FAQ', icon: MessageSquare, color: 'bg-green-100 text-green-700' },
  product_description: { label: 'Product', icon: FileText, color: 'bg-amber-100 text-amber-700' },
  landing_page: { label: 'Landing Page', icon: FileText, color: 'bg-purple-100 text-purple-700' },
  schema_markup: { label: 'Schema', icon: Code2, color: 'bg-orange-100 text-orange-700' },
  social_post: { label: 'Social', icon: Share2, color: 'bg-pink-100 text-pink-700' },
  review_response: { label: 'Review', icon: Star, color: 'bg-yellow-100 text-yellow-700' },
}

const OUTPUT_TYPE_META: Record<string, { label: string; icon: React.ComponentType<{ className?: string }>; color: string }> = {
  competitor_report: { label: 'Competitor Report', icon: BarChart3, color: 'bg-orange-100 text-orange-700' },
  query_suggestions: { label: 'Query Suggestions', icon: Search, color: 'bg-green-100 text-green-700' },
  review_analysis: { label: 'Review Analysis', icon: Star, color: 'bg-amber-100 text-amber-700' },
  social_strategy: { label: 'Social Strategy', icon: Share2, color: 'bg-pink-100 text-pink-700' },
  schema_recommendations: { label: 'Schema Recs', icon: Code2, color: 'bg-purple-100 text-purple-700' },
}

interface ContentLibraryViewProps {
  content: Array<{
    id: string
    content_type: string
    title: string | null
    content_format: string
    word_count: number | null
    quality_score: number | null
    is_favorited: boolean
    created_at: string
  }>
  outputs: Array<{
    id: string
    output_type: string
    title: string | null
    summary: string | null
    is_favorited: boolean
    created_at: string
  }>
}

type Tab = 'all' | 'content' | 'reports'

export function ContentLibraryView({ content, outputs }: ContentLibraryViewProps) {
  const [tab, setTab] = useState<Tab>('all')
  const [searchQuery, setSearchQuery] = useState('')

  const filteredContent = content.filter((c) =>
    !searchQuery || (c.title ?? '').toLowerCase().includes(searchQuery.toLowerCase())
  )
  const filteredOutputs = outputs.filter((o) =>
    !searchQuery || (o.title ?? '').toLowerCase().includes(searchQuery.toLowerCase()) || (o.summary ?? '').toLowerCase().includes(searchQuery.toLowerCase())
  )

  const showContent = tab === 'all' || tab === 'content'
  const showOutputs = tab === 'all' || tab === 'reports'
  const totalItems = content.length + outputs.length

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold text-[var(--color-text)]">
          Content Library
        </h1>
        <p className="text-sm text-[var(--color-muted)]">
          {totalItems} item{totalItems !== 1 ? 's' : ''} generated by your AI agents
        </p>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-muted)]" />
          <Input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search content..."
            className="pl-10"
          />
        </div>
        <div className="flex gap-1 rounded-lg border border-[var(--color-card-border)] p-1">
          {(['all', 'content', 'reports'] as Tab[]).map((t) => (
            <Button
              key={t}
              variant={tab === t ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setTab(t)}
              className={tab === t ? 'bg-[var(--color-accent)] text-white' : ''}
            >
              {t === 'all' ? 'All' : t === 'content' ? 'Content' : 'Reports'}
            </Button>
          ))}
        </div>
      </div>

      {/* Items */}
      {totalItems === 0 ? (
        <div className="py-16 text-center">
          <FileText className="mx-auto h-12 w-12 text-[var(--color-card-border)]" />
          <h2 className="mt-4 font-display text-lg font-semibold text-[var(--color-text)]">
            No content yet
          </h2>
          <p className="mt-1 text-sm text-[var(--color-muted)]">
            Run an AI agent to generate your first piece of content.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {showContent && filteredContent.map((item) => {
            const meta = CONTENT_TYPE_META[item.content_type] ?? { label: item.content_type, icon: FileText, color: 'bg-gray-100 text-gray-700' }
            const Icon = meta.icon
            return (
              <Card key={item.id} className="border-[var(--color-card-border)]" style={{ borderRadius: 'var(--card-radius)' }}>
                <CardContent className="flex items-center gap-4 p-4">
                  <div className={`flex h-10 w-10 items-center justify-center rounded-xl shrink-0 ${meta.color}`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-[var(--color-text)] truncate">
                      {item.title ?? 'Untitled'}
                    </p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge className={`text-xs ${meta.color}`}>{meta.label}</Badge>
                      {item.word_count && (
                        <span className="text-xs text-[var(--color-muted)]">{item.word_count} words</span>
                      )}
                      {item.quality_score !== null && (
                        <span className="text-xs text-[var(--color-muted)]">Quality: {item.quality_score}%</span>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {item.is_favorited && <Heart className="h-4 w-4 text-red-500 fill-red-500" />}
                    <span className="text-xs text-[var(--color-muted)]">
                      {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                    </span>
                  </div>
                </CardContent>
              </Card>
            )
          })}

          {showOutputs && filteredOutputs.map((item) => {
            const meta = OUTPUT_TYPE_META[item.output_type] ?? { label: item.output_type, icon: BarChart3, color: 'bg-gray-100 text-gray-700' }
            const Icon = meta.icon
            return (
              <Card key={item.id} className="border-[var(--color-card-border)]" style={{ borderRadius: 'var(--card-radius)' }}>
                <CardContent className="flex items-center gap-4 p-4">
                  <div className={`flex h-10 w-10 items-center justify-center rounded-xl shrink-0 ${meta.color}`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-[var(--color-text)] truncate">
                      {item.title ?? 'Untitled Report'}
                    </p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge className={`text-xs ${meta.color}`}>{meta.label}</Badge>
                      {item.summary && (
                        <span className="text-xs text-[var(--color-muted)] truncate max-w-xs">{item.summary}</span>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {item.is_favorited && <Heart className="h-4 w-4 text-red-500 fill-red-500" />}
                    <span className="text-xs text-[var(--color-muted)]">
                      {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                    </span>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
