'use client'

import { useState, useCallback } from 'react'
import { useRouter } from 'next/navigation'

interface ContentItem {
  id: string
  title: string
  content_body: string | null
  content_format: string | null
  status: string
  agent_type: string | null
  word_count: number | null
  meta_description: string | null
  tags: string[] | null
  created_at: string
  updated_at: string | null
}

interface ContentEditorViewProps {
  item: ContentItem
}

type EditorTab = 'edit' | 'preview'

export function ContentEditorView({ item }: ContentEditorViewProps) {
  const router = useRouter()
  const [title, setTitle] = useState(item.title)
  const [body, setBody] = useState(item.content_body ?? '')
  const [metaDescription, setMetaDescription] = useState(item.meta_description ?? '')
  const [activeTab, setActiveTab] = useState<EditorTab>('edit')
  const [isSaving, setIsSaving] = useState(false)
  const [isPublishing, setIsPublishing] = useState(false)
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saved' | 'error'>('idle')

  const wordCount = body.split(/\s+/).filter(Boolean).length
  const hasChanges = title !== item.title || body !== (item.content_body ?? '') || metaDescription !== (item.meta_description ?? '')

  const handleSave = useCallback(async () => {
    setIsSaving(true)
    setSaveStatus('idle')

    try {
      const res = await fetch(`/api/content/${item.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          content_body: body,
          meta_description: metaDescription || null,
          change_summary: 'Manual edit',
        }),
      })

      if (res.ok) {
        setSaveStatus('saved')
        setTimeout(() => setSaveStatus('idle'), 2000)
      } else {
        setSaveStatus('error')
      }
    } catch {
      setSaveStatus('error')
    } finally {
      setIsSaving(false)
    }
  }, [item.id, title, body, metaDescription])

  async function handlePublish() {
    setIsPublishing(true)
    try {
      const res = await fetch(`/api/content/${item.id}/publish`, { method: 'POST' })
      if (res.ok) {
        router.refresh()
      }
    } catch {
      // Silently fail
    } finally {
      setIsPublishing(false)
    }
  }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <button
            onClick={() => router.push('/dashboard/content')}
            className="text-stone-400 hover:text-stone-600"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="m15 18-6-6 6-6" />
            </svg>
          </button>
          <div>
            <h1 className="text-xl font-bold text-[#141310]">Edit Content</h1>
            <div className="flex items-center gap-2 mt-0.5">
              {item.agent_type && (
                <span className="text-xs text-stone-400">
                  Generated by {item.agent_type.replace(/_/g, ' ')}
                </span>
              )}
              <span
                className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                  item.status === 'published'
                    ? 'bg-green-100 text-green-700'
                    : item.status === 'draft'
                      ? 'bg-stone-100 text-stone-600'
                      : 'bg-amber-100 text-amber-700'
                }`}
              >
                {item.status}
              </span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {saveStatus === 'saved' && (
            <span className="text-green-600 text-sm">Saved</span>
          )}
          {saveStatus === 'error' && (
            <span className="text-red-600 text-sm">Failed to save</span>
          )}
          <button
            onClick={handleSave}
            disabled={isSaving || !hasChanges}
            className="px-4 py-2 border border-stone-200 text-[#141310] text-sm rounded-lg hover:bg-stone-50 disabled:opacity-50"
          >
            {isSaving ? 'Saving...' : 'Save Draft'}
          </button>
          {item.status !== 'published' && (
            <button
              onClick={handlePublish}
              disabled={isPublishing}
              className="px-4 py-2 bg-[#141310] text-white text-sm rounded-lg hover:bg-stone-800 disabled:opacity-50"
            >
              {isPublishing ? 'Publishing...' : 'Publish'}
            </button>
          )}
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-stone-200 overflow-hidden">
        <div className="border-b border-stone-200 p-4">
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full text-lg font-semibold text-[#141310] focus:outline-none"
            placeholder="Content title"
          />
          <input
            type="text"
            value={metaDescription}
            onChange={(e) => setMetaDescription(e.target.value)}
            className="w-full text-sm text-stone-500 mt-2 focus:outline-none"
            placeholder="Meta description (optional)"
          />
        </div>

        <div className="flex border-b border-stone-200">
          {(['edit', 'preview'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 text-sm border-b-2 transition-colors ${
                activeTab === tab
                  ? 'border-[#141310] text-[#141310] font-medium'
                  : 'border-transparent text-stone-400 hover:text-stone-600'
              }`}
            >
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
          <div className="ml-auto px-4 py-2 text-xs text-stone-400">
            {wordCount} words
          </div>
        </div>

        <div className="p-4 min-h-[400px]">
          {activeTab === 'edit' ? (
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="w-full h-[400px] text-sm text-[#141310] font-mono leading-relaxed resize-none focus:outline-none"
              placeholder="Write your content in Markdown..."
            />
          ) : (
            <div className="prose prose-stone max-w-none text-sm">
              {body ? (
                <div className="whitespace-pre-wrap">{body}</div>
              ) : (
                <p className="text-stone-400 italic">Nothing to preview yet.</p>
              )}
            </div>
          )}
        </div>
      </div>

      {item.tags && item.tags.length > 0 && (
        <div className="mt-4 flex items-center gap-2">
          <span className="text-xs text-stone-400">Tags:</span>
          {item.tags.map((tag) => (
            <span
              key={tag}
              className="px-2 py-0.5 rounded-full text-xs bg-stone-100 text-stone-500"
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  )
}
