'use client'

import { useState, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface ContentItem {
  id: string
  title: string
  content_body: string | null
  content_format: string | null
  status: string
  agent_type: string | null
  word_count: number | null
  meta_description: string | null
  tags: string[] | null
  created_at: string
  updated_at: string | null
}

interface ContentEditorViewProps {
  item: ContentItem
}

type EditorTab = 'edit' | 'preview'

const STATUS_META: Record<string, { label: string; class: string }> = {
  published: { label: 'Published', class: 'bg-green-100 text-green-700' },
  draft: { label: 'Draft', class: 'bg-muted text-muted-foreground' },
  ready: { label: 'Ready', class: 'bg-amber-100 text-amber-700' },
}

export function ContentEditorView({ item }: ContentEditorViewProps) {
  const router = useRouter()
  const [title, setTitle] = useState(item.title)
  const [body, setBody] = useState(item.content_body ?? '')
  const [metaDescription, setMetaDescription] = useState(item.meta_description ?? '')
  const [activeTab, setActiveTab] = useState<EditorTab>('edit')
  const [isSaving, setIsSaving] = useState(false)
  const [isPublishing, setIsPublishing] = useState(false)
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saved' | 'error'>('idle')
  const [publishError, setPublishError] = useState<string | null>(null)

  const wordCount = body.split(/\s+/).filter(Boolean).length
  const hasChanges =
    title !== item.title ||
    body !== (item.content_body ?? '') ||
    metaDescription !== (item.meta_description ?? '')

  const statusMeta = STATUS_META[item.status] ?? {
    label: item.status,
    class: 'bg-muted text-muted-foreground',
  }

  const handleSave = useCallback(async () => {
    setIsSaving(true)
    setSaveStatus('idle')

    try {
      const res = await fetch(`/api/content/${item.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          content_body: body,
          meta_description: metaDescription || null,
          change_summary: 'Manual edit',
        }),
      })

      if (res.ok) {
        setSaveStatus('saved')
        setTimeout(() => setSaveStatus('idle'), 2000)
      } else {
        setSaveStatus('error')
      }
    } catch {
      setSaveStatus('error')
    } finally {
      setIsSaving(false)
    }
  }, [item.id, title, body, metaDescription])

  async function handlePublish() {
    setIsPublishing(true)
    setPublishError(null)
    try {
      const res = await fetch(`/api/content/${item.id}/publish`, { method: 'POST' })
      if (res.ok) {
        router.refresh()
      } else {
        setPublishError('Failed to publish. Please try again.')
      }
    } catch {
      setPublishError('Network error. Please check your connection.')
    } finally {
      setIsPublishing(false)
    }
  }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 gap-4 flex-wrap">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.push('/dashboard/content')}
            className="h-8 w-8 p-0"
            aria-label="Back to content library"
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-xl font-medium text-foreground">Edit Content</h1>
            <div className="flex items-center gap-2 mt-0.5 flex-wrap">
              {item.agent_type && (
                <span className="text-xs text-muted-foreground">
                  Generated by {item.agent_type.replace(/_/g, ' ')}
                </span>
              )}
              <span
                className={cn(
                  'px-2 py-0.5 rounded-full text-xs font-medium',
                  statusMeta.class,
                )}
              >
                {statusMeta.label}
              </span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {saveStatus === 'saved' && (
            <span className="text-[var(--color-score-good)] text-sm font-medium">Saved</span>
          )}
          {saveStatus === 'error' && (
            <span className="text-destructive text-sm">Failed to save</span>
          )}
          <Button
            variant="ghost"
            size="sm"
            onClick={handleSave}
            disabled={isSaving || !hasChanges}
          >
            {isSaving ? 'Saving...' : 'Save Draft'}
          </Button>
          {item.status !== 'published' && (
            <Button
              variant="default"
              size="sm"
              onClick={handlePublish}
              disabled={isPublishing}
              className="bg-primary text-primary-foreground hover:bg-primary/90"
            >
              {isPublishing ? 'Publishing...' : 'Publish'}
            </Button>
          )}
        </div>
      </div>
      {publishError && (
        <p className="text-sm text-red-500 mb-4">{publishError}</p>
      )}

      {/* Editor card */}
      <div className="bg-card rounded-lg border border-border shadow-sm overflow-hidden">
        {/* Title + meta */}
        <div className="border-b border-border p-6">
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full text-lg font-medium text-foreground bg-transparent focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded"
            placeholder="Content title"
            aria-label="Content title"
          />
          <input
            type="text"
            value={metaDescription}
            onChange={(e) => setMetaDescription(e.target.value)}
            className="w-full text-sm text-muted-foreground bg-transparent mt-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded"
            placeholder="Meta description (optional)"
            aria-label="Meta description"
          />
        </div>

        {/* Tab bar */}
        <div className="flex border-b border-border">
          {(['edit', 'preview'] as const).map((tabKey) => (
            <button
              key={tabKey}
              onClick={() => setActiveTab(tabKey)}
              className={cn(
                'px-5 py-3 text-sm border-b-2 transition-colors',
                activeTab === tabKey
                  ? 'border-primary text-foreground font-medium'
                  : 'border-transparent text-muted-foreground hover:text-foreground',
              )}
            >
              {tabKey.charAt(0).toUpperCase() + tabKey.slice(1)}
            </button>
          ))}
          <div className="ml-auto px-5 py-3 text-xs text-muted-foreground flex items-center">
            {wordCount} words
          </div>
        </div>

        {/* Editor / preview area */}
        <div className="p-6 min-h-[400px]">
          {activeTab === 'edit' ? (
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="w-full h-[400px] text-sm text-foreground font-mono leading-relaxed resize-none bg-transparent focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded"
              placeholder="Write your content in Markdown..."
              aria-label="Content body"
            />
          ) : (
            <div className="prose prose-stone max-w-none text-sm">
              {body ? (
                <div className="whitespace-pre-wrap text-foreground">{body}</div>
              ) : (
                <p className="text-muted-foreground italic">Nothing to preview yet.</p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Tags */}
      {item.tags && item.tags.length > 0 && (
        <div className="mt-4 flex items-center gap-2 flex-wrap">
          <span className="text-xs text-muted-foreground">Tags:</span>
          {item.tags.map((tag) => (
            <span
              key={tag}
              className="px-2 py-0.5 rounded-full text-xs bg-muted text-muted-foreground"
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  )
}
