'use client'

import { useState } from 'react'
import {
  FileText,
  BookOpen,
  Code2,
  Star,
  Heart,
  Search,
  BarChart3,
  MessageSquare,
  Share2,
} from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { EmptyState } from '@/components/ui/empty-state'
import { PageHeader } from '@/components/ui/page-header'
import { cn } from '@/lib/utils'
import { formatDistanceToNow } from 'date-fns'

const CONTENT_TYPE_META: Record<
  string,
  { label: string; icon: React.ComponentType<{ className?: string }>; color: string }
> = {
  blog_post: { label: 'Blog Post', icon: BookOpen, color: 'bg-blue-100 text-blue-700' },
  article: { label: 'Article', icon: FileText, color: 'bg-orange-100 text-orange-700' },
  faq: { label: 'FAQ', icon: MessageSquare, color: 'bg-green-100 text-green-700' },
  product_description: { label: 'Product', icon: FileText, color: 'bg-amber-100 text-amber-700' },
  landing_page: { label: 'Landing Page', icon: FileText, color: 'bg-purple-100 text-purple-700' },
  schema_markup: { label: 'Schema', icon: Code2, color: 'bg-orange-100 text-orange-700' },
  social_post: { label: 'Social', icon: Share2, color: 'bg-pink-100 text-pink-700' },
  review_response: { label: 'Review', icon: Star, color: 'bg-yellow-100 text-yellow-700' },
}

const OUTPUT_TYPE_META: Record<
  string,
  { label: string; icon: React.ComponentType<{ className?: string }>; color: string }
> = {
  competitor_report: {
    label: 'Competitor Report',
    icon: BarChart3,
    color: 'bg-orange-100 text-orange-700',
  },
  query_suggestions: {
    label: 'Query Suggestions',
    icon: Search,
    color: 'bg-green-100 text-green-700',
  },
  review_analysis: {
    label: 'Review Analysis',
    icon: Star,
    color: 'bg-amber-100 text-amber-700',
  },
  social_strategy: {
    label: 'Social Strategy',
    icon: Share2,
    color: 'bg-pink-100 text-pink-700',
  },
  schema_recommendations: {
    label: 'Schema Recs',
    icon: Code2,
    color: 'bg-purple-100 text-purple-700',
  },
}

interface ContentLibraryViewProps {
  content: Array<{
    id: string
    agent_type: string
    title: string
    content_format: string
    word_count: number | null
    quality_score: number | null
    is_favorited: boolean
    created_at: string
  }>
  outputs: Array<{
    id: string
    agent_type: string
    status: string
    created_at: string
    completed_at: string | null
  }>
}

type Tab = 'all' | 'content' | 'reports'

const STATUS_META: Record<string, { label: string; class: string }> = {
  draft: { label: 'Draft', class: 'bg-muted text-muted-foreground' },
  ready: { label: 'Ready', class: 'bg-amber-100 text-amber-700' },
  published: { label: 'Published', class: 'bg-green-100 text-green-700' },
  completed: { label: 'Completed', class: 'bg-green-100 text-green-700' },
  failed: { label: 'Failed', class: 'bg-red-100 text-red-700' },
  running: { label: 'Running', class: 'bg-blue-100 text-blue-700' },
}

export function ContentLibraryView({ content, outputs }: ContentLibraryViewProps) {
  const [tab, setTab] = useState<Tab>('all')
  const [searchQuery, setSearchQuery] = useState('')

  const filteredContent = content.filter(
    (c) => !searchQuery || c.title.toLowerCase().includes(searchQuery.toLowerCase()),
  )
  const filteredOutputs = outputs.filter(
    (o) => !searchQuery || o.agent_type.toLowerCase().includes(searchQuery.toLowerCase()),
  )

  const showContent = tab === 'all' || tab === 'content'
  const showOutputs = tab === 'all' || tab === 'reports'
  const totalItems = content.length + outputs.length

  const visibleCount =
    (showContent ? filteredContent.length : 0) + (showOutputs ? filteredOutputs.length : 0)

  return (
    <div className="space-y-6">
      <PageHeader
        title="Content Library"
        description={`${totalItems} item${totalItems !== 1 ? 's' : ''} generated by your AI agents`}
      />

      {/* Filters */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search content..."
            className="pl-10"
            aria-label="Search content"
          />
        </div>
        <div className="flex gap-1 rounded-lg border border-border bg-background p-1 w-fit">
          {(['all', 'content', 'reports'] as Tab[]).map((t) => (
            <Button
              key={t}
              variant={tab === t ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setTab(t)}
              className={cn(
                tab === t && 'bg-primary text-primary-foreground hover:bg-primary/90',
              )}
            >
              {t === 'all' ? 'All' : t === 'content' ? 'Content' : 'Reports'}
            </Button>
          ))}
        </div>
      </div>

      {/* Items */}
      {totalItems === 0 ? (
        <div className="rounded-[20px] border-2 border-dashed border-border">
          <EmptyState
            icon={FileText}
            title="No content yet"
            description="Run an AI agent to generate your first piece of content."
          />
        </div>
      ) : visibleCount === 0 ? (
        <div className="rounded-[20px] border-2 border-dashed border-border">
          <EmptyState
            icon={Search}
            title="No results found"
            description="Try a different search term or switch tabs."
          />
        </div>
      ) : (
        <div className="space-y-3">
          {showContent &&
            filteredContent.map((item) => {
              const meta = CONTENT_TYPE_META[item.agent_type] ?? {
                label: item.agent_type,
                icon: FileText,
                color: 'bg-muted text-muted-foreground',
              }
              const Icon = meta.icon
              return (
                <Card
                  key={item.id}
                  className="bg-card rounded-[20px] border border-border shadow-sm hover:shadow-md hover:-translate-y-0.5 transition-all duration-200 cursor-pointer"
                >
                  <CardContent className="flex items-center gap-4 p-4">
                    <div
                      className={cn(
                        'flex h-10 w-10 items-center justify-center rounded-xl shrink-0',
                        meta.color,
                      )}
                    >
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">{item.title}</p>
                      <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                        <Badge className={cn('text-xs border-0', meta.color)}>{meta.label}</Badge>
                        {item.word_count && (
                          <span className="text-xs text-muted-foreground">
                            {item.word_count} words
                          </span>
                        )}
                        {item.quality_score !== null && (
                          <span className="text-xs text-muted-foreground">
                            Quality: {item.quality_score}%
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      {item.is_favorited && (
                        <Heart className="h-4 w-4 text-red-500 fill-red-500" aria-label="Favorited" />
                      )}
                      <span className="text-xs text-muted-foreground">
                        {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              )
            })}

          {showOutputs &&
            filteredOutputs.map((item) => {
              const meta = OUTPUT_TYPE_META[item.agent_type] ?? {
                label: item.agent_type,
                icon: BarChart3,
                color: 'bg-muted text-muted-foreground',
              }
              const statusMeta = STATUS_META[item.status] ?? {
                label: item.status,
                class: 'bg-muted text-muted-foreground',
              }
              const Icon = meta.icon
              return (
                <Card
                  key={item.id}
                  className="bg-card rounded-[20px] border border-border shadow-sm hover:shadow-md hover:-translate-y-0.5 transition-all duration-200 cursor-pointer"
                >
                  <CardContent className="flex items-center gap-4 p-4">
                    <div
                      className={cn(
                        'flex h-10 w-10 items-center justify-center rounded-xl shrink-0',
                        meta.color,
                      )}
                    >
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">{meta.label}</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        <Badge className={cn('text-xs border-0', statusMeta.class)}>
                          {statusMeta.label}
                        </Badge>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <span className="text-xs text-muted-foreground">
                        {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              )
            })}
        </div>
      )}
    </div>
  )
}
