/**
 * Console Surface Fixtures — Shared Types
 *
 * Interfaces used by each surface's fixture file.
 * Surface workers extend within their own file; they do NOT edit this file.
 *
 * Business identity const — re-exported so all surfaces tell the same story.
 */

// ---------------------------------------------------------------------------
// Business identity (Bright Smile Dental, Ramat Gan)
// ---------------------------------------------------------------------------
export const DEMO_BUSINESS = {
  name: 'Bright Smile Dental',
  website: 'brightsmile-dental.co.il',
  location: 'Ramat Gan, Israel',
} as const

// ---------------------------------------------------------------------------
// Prompts surface
// ---------------------------------------------------------------------------

export interface PromptRow {
  id: string
  query: string
  /** Number of times this query appeared across AI engines */
  frequency: number
  /** Engines that cited a competitor for this query */
  competitorEngines: string[]
  /** Number of co-citations for this query */
  coCitations: number
  intent: 'informational' | 'transactional' | 'navigational'
  /** true = Beamix has content targeting this query */
  covered: boolean
}

export interface PromptDrawerData {
  promptId: string
  query: string
  /** Fan-out TREE: citations for this query across engines */
  tree: {
    engine: string
    citations: { domain: string; title: string; snippet: string }[]
  }[]
  intent: PromptRow['intent']
  /** Uncited gap — no current content targets this angle */
  gapDescription: string | null
}

// ---------------------------------------------------------------------------
// Content surface
// ---------------------------------------------------------------------------

export interface ContentDoc {
  id: string
  url: string
  title: string
  /** 'optimize' | 'refresh' | 'faq' */
  tab: 'optimize' | 'refresh' | 'faq'
  /** Current word count */
  wordCount: number
  /** Days since last update */
  daysSinceUpdate: number
  /** AI visibility score for this page */
  visibilityScore: number
  /** true = page-lock is active (another agent is using this page) */
  pageLocked: boolean
}

export interface ContentDiff {
  docId: string
  before: string
  after: string
  /** Markdown formatted diff lines */
  diffLines: { type: 'unchanged' | 'added' | 'removed'; content: string }[]
}

// ---------------------------------------------------------------------------
// Schema surface
// ---------------------------------------------------------------------------

export interface SchemaResult {
  id: string
  url: string
  schemaType: string
  /** Validity percentage 0-100 */
  validityScore: number
  /** JSON-LD string */
  jsonLd: string
  missingFields: string[]
  /** true = auto-published, false = pending inject */
  published: boolean
  publishedAt: string | null
}

// ---------------------------------------------------------------------------
// Run History surface
// ---------------------------------------------------------------------------

export interface RunRow {
  id: string
  agentLabel: string
  /** 'myself' | 'beamix' */
  mode: 'myself' | 'beamix'
  status: 'success' | 'failed' | 'running'
  timestamp: string
  /** USD cost */
  costUsd: number
  /** One-line output preview */
  snippet: string
}

export interface RunTrace {
  runId: string
  stages: {
    id: string
    label: string
    status: 'done' | 'error'
    substep: string
    durationMs: number
  }[]
  outputSnippet: string
}

// ---------------------------------------------------------------------------
// Competitors surface
// ---------------------------------------------------------------------------

export interface CompetitorRow {
  id: string
  name: string
  domain: string
  /** Share of voice across all tracked queries, 0-100 */
  shareOfVoice: number
  /** Which engines cite this competitor */
  engines: string[]
  /** Number of queries where this competitor appears but we don't */
  gapCount: number
}

export interface ShareOfVoicePoint {
  /** ISO date string */
  date: string
  /** Our share of voice 0-100 */
  us: number
  /** Leading competitor's share of voice 0-100 */
  topCompetitor: number
}

// ---------------------------------------------------------------------------
// Automation surface (Mode Hub)
// ---------------------------------------------------------------------------

export interface AutomationRow {
  id: string
  agentLabel: string
  /** Current run mode */
  mode: 'myself' | 'beamix'
  /** Schedule label e.g. "Weekly · Mondays 9am" */
  scheduleLabel: string | null
  /** Allotment remaining */
  allotmentLabel: string | null
  /** ISO timestamp of last run */
  lastRunAt: string | null
  /** href to the tool page */
  toolHref: string
}

// ---------------------------------------------------------------------------
// Off-Site surface
// ---------------------------------------------------------------------------

export interface OffsiteRow {
  id: string
  /** 'citation' | 'directory' | 'entity' | 'reputation' | 'community' */
  tab: 'citation' | 'directory' | 'entity' | 'reputation' | 'community'
  title: string
  domain: string
  /** 'tracked' | 'untracked' | 'submitted' */
  status: 'tracked' | 'untracked' | 'submitted'
  /** Importance score 0-100 */
  importance: number
}

// ---------------------------------------------------------------------------
// Blog Studio surface
// ---------------------------------------------------------------------------

export interface BlogDraft {
  id: string
  topic: string
  /** Tier-locked on Discover */
  locked: boolean
  /** Word count target */
  targetWordCount: number
  /** ISO timestamp when draft was last saved */
  lastSavedAt: string | null
  /** Markdown content */
  content: string
  status: 'draft' | 'pending_approval' | 'approved'
}
