/**
 * Console Surface Fixtures — Shared Types
 *
 * Interfaces used by each surface's fixture file.
 * Surface workers extend within their own file; they do NOT edit this file.
 *
 * Business identity const — re-exported so all surfaces tell the same story.
 */

// ---------------------------------------------------------------------------
// Business identity (Bright Smile Dental, Ramat Gan)
// ---------------------------------------------------------------------------
export const DEMO_BUSINESS = {
  name: 'Bright Smile Dental',
  website: 'brightsmile-dental.co.il',
  location: 'Ramat Gan, Israel',
} as const

// ---------------------------------------------------------------------------
// Prompts surface
// ---------------------------------------------------------------------------

export interface PromptRow {
  id: string
  query: string
  /** Number of times this query appeared across AI engines */
  frequency: number
  /** Engines that cited a competitor for this query */
  competitorEngines: string[]
  /** Number of co-citations for this query */
  coCitations: number
  intent: 'informational' | 'transactional' | 'navigational'
  /** true = Beamix has content targeting this query */
  covered: boolean
}

export interface PromptDrawerData {
  promptId: string
  query: string
  /** Fan-out TREE: citations for this query across engines */
  tree: {
    engine: string
    citations: { domain: string; title: string; snippet: string }[]
  }[]
  intent: PromptRow['intent']
  /** Uncited gap — no current content targets this angle */
  gapDescription: string | null
}

// ---------------------------------------------------------------------------
// Content surface
// ---------------------------------------------------------------------------

export interface ContentDoc {
  id: string
  url: string
  title: string
  /** 'optimize' | 'refresh' | 'faq' */
  tab: 'optimize' | 'refresh' | 'faq'
  /** Current word count */
  wordCount: number
  /** Days since last update */
  daysSinceUpdate: number
  /** AI visibility score for this page */
  visibilityScore: number
  /** true = page-lock is active (another agent is using this page) */
  pageLocked: boolean
}

export interface ContentDiff {
  docId: string
  before: string
  after: string
  /** Markdown formatted diff lines */
  diffLines: { type: 'unchanged' | 'added' | 'removed'; content: string }[]
}

// ---------------------------------------------------------------------------
// Schema surface
// ---------------------------------------------------------------------------

export interface SchemaResult {
  id: string
  url: string
  schemaType: string
  /** Validity percentage 0-100 */
  validityScore: number
  /** JSON-LD string */
  jsonLd: string
  missingFields: string[]
  /** true = auto-published, false = pending inject */
  published: boolean
  publishedAt: string | null
  /** Target URL or integration name where the schema was auto-published */
  publishTarget?: string
}

// ---------------------------------------------------------------------------
// Run History surface
// ---------------------------------------------------------------------------

export interface RunRow {
  id: string
  agentLabel: string
  /** 'myself' | 'beamix' */
  mode: 'myself' | 'beamix'
  status: 'success' | 'failed' | 'running'
  timestamp: string
  /** USD cost */
  costUsd: number
  /** One-line output preview */
  snippet: string
}

export interface RunTrace {
  runId: string
  stages: {
    id: string
    label: string
    status: 'done' | 'error'
    substep: string
    durationMs: number
  }[]
  outputSnippet: string
}

// ---------------------------------------------------------------------------
// Competitors surface
// ---------------------------------------------------------------------------

export interface CompetitorRow {
  id: string
  name: string
  domain: string
  /** Share of voice across all tracked queries, 0-100 */
  shareOfVoice: number
  /** Which engines cite this competitor */
  engines: string[]
  /** Number of queries where this competitor appears but we don't */
  gapCount: number
}

export interface ShareOfVoicePoint {
  /** ISO date string */
  date: string
  /** Our share of voice 0-100 */
  us: number
  /** Leading competitor's share of voice 0-100 */
  topCompetitor: number
}

// ---------------------------------------------------------------------------
// Automation surface (Mode Hub)
// ---------------------------------------------------------------------------

export interface AutomationRow {
  id: string
  agentLabel: string
  /** Current run mode */
  mode: 'myself' | 'beamix'
  /** Schedule label e.g. "Weekly · Mondays 9am" */
  scheduleLabel: string | null
  /** Allotment remaining */
  allotmentLabel: string | null
  /** ISO timestamp of last run */
  lastRunAt: string | null
  /** href to the tool page */
  toolHref: string
}

// ---------------------------------------------------------------------------
// Off-Site surface
// ---------------------------------------------------------------------------

export interface OffsiteRow {
  id: string
  /** 'citation' | 'directory' | 'entity' | 'reputation' | 'community' */
  tab: 'citation' | 'directory' | 'entity' | 'reputation' | 'community'
  title: string
  domain: string
  /** 'tracked' | 'untracked' | 'submitted' */
  status: 'tracked' | 'untracked' | 'submitted'
  /** Importance score 0-100 */
  importance: number
}

// ---------------------------------------------------------------------------
// Blog Studio surface
// ---------------------------------------------------------------------------

export interface BlogDraft {
  id: string
  topic: string
  /** Tier-locked on Discover */
  locked: boolean
  /** Word count target */
  targetWordCount: number
  /** ISO timestamp when draft was last saved */
  lastSavedAt: string | null
  /** Markdown content */
  content: string
  status: 'draft' | 'pending_approval' | 'approved'
}

// ---------------------------------------------------------------------------
// Analytics surface
// ---------------------------------------------------------------------------

/**
 * A single weekly snapshot of engine visibility values + an optional
 * violet agent-event annotation (rendered as a Recharts ReferenceLine).
 */
export interface EngineVisibilityPoint {
  /** ISO date string (weekly cadence) */
  date: string
  /** Per-engine visibility 0–100 (keyed by engine name) */
  values: Record<string, number>
  /** Violet annotation when an agent ran this week */
  agentEvent?: { label: string } | null
}

/**
 * A single weekly Share-of-Voice snapshot for the stacked competitor chart.
 */
export interface SovTrendPoint {
  /** ISO date string */
  date: string
  /** Our SoV 0–100 */
  us: number
  /** Per-competitor SoV stacked values (keyed by competitor name) */
  competitors: Record<string, number>
  /** Violet annotation when an agent ran this week */
  agentEvent?: { label: string } | null
}

/** Per-engine average position + sparkline for the position table */
export interface AvgPositionStat {
  engine: string
  /** Average rank position (lower = better), e.g. 1.4 */
  avgPosition: number
  /** Optional 5-point sparkline of recent avg positions (lower = better) */
  sparkline: number[] | null
}

/** A single cell in the topic × engine ranking matrix */
export interface TopicRankCell {
  topic: string
  engine: string
  /** Average rank position for this topic on this engine */
  avgRank: number
  /** Visual score band */
  scoreBand: 'excellent' | 'good' | 'fair' | 'critical'
}

/** Drill data surfaced in the AnalyticsDrillDrawer for a given topic/engine cell */
export interface AnalyticsDrillData {
  topic: string
  engine: string
  /** Representative prompts tested for this topic/engine pair */
  promptsTested: string[]
  /** Snippet Beamix currently surfaces in this engine for this topic */
  ourSnippet: string
  /** Snippet from the leading competitor for this topic/engine pair */
  competitorSnippet: string
  competitorName: string
  /** Optional agent recommendation shown at the bottom of the drawer */
  agentNote?: string | null
}

/** Top-level shape for the Analytics surface fixture */
export interface DemoAnalytics {
  /** Hero SoV percentage (current period) */
  heroSov: number
  /** Delta vs. previous 30-day period (+/−) */
  sovDelta: number
  /** 8 weekly trend points — per-engine visibility */
  visibilityTrend: EngineVisibilityPoint[]
  /** 8 weekly trend points — SoV stacked view */
  sovTrend: SovTrendPoint[]
  /** Per-engine average positions (current period) */
  avgPositions: AvgPositionStat[]
  /** Flat list of all topic × engine rank cells (6 topics × 5 engines) */
  topicMatrix: TopicRankCell[]
  /** Pre-built drill datasets keyed by "${topic}__${engine}" */
  drillData: Record<string, AnalyticsDrillData>
}

// ---------------------------------------------------------------------------
// Sentiment surface
// ---------------------------------------------------------------------------

/** A verbatim AI response snippet about the business */
export interface VerbatimQuote {
  engine: string
  /** ISO date string of when the response was captured */
  date: string
  /** The user prompt that generated this response */
  prompt: string
  /** The full AI response text (2–3 sentences, real-feeling) */
  fullResponse: string
  sentiment: 'positive' | 'neutral' | 'negative'
  /** The specific clause flagged as inaccurate or problematic */
  flaggedClause?: string | null
  /** Linked claim ID for cross-referencing ClaimAccuracyRow */
  claimId?: string | null
}

/** Positive/neutral/negative split percentages */
export interface SentimentSplit {
  positive: number
  neutral: number
  negative: number
}

/** A recurring theme in how AI engines describe the business */
export interface SentimentTheme {
  name: string
  sentiment: 'positive' | 'neutral' | 'negative'
  /** Number of AI responses that reference this theme */
  mentionCount: number
  /** A representative verbatim quote for this theme */
  representativeQuote: VerbatimQuote
}

/** A claim accuracy issue found in AI engine responses */
export interface ClaimAccuracyRow {
  id: string
  /** The false or misleading claim text */
  claim: string
  severity: 'critical' | 'warning' | 'info'
  /** Which engines are making this claim */
  engines: string[]
  /** ISO date first detected */
  date: string
  /** Href to the agent action that corrects this claim */
  correctHref: string
}

/** A before/after recovery event showing a previously-wrong claim now corrected */
export interface RecoveryEvent {
  wrongQuote: string
  wrongDate: string
  correctedQuote: string
  correctedDate: string
  /** Engine where the correction was observed */
  engine: string
}

/** Top-level shape for the Sentiment surface fixture */
export interface DemoSentiment {
  /** Integrity score 0–100 */
  integrityScore: number
  /** Score band */
  integrityBand: 'excellent' | 'good' | 'fair' | 'critical'
  /**
   * Recent integrity-score history (oldest → newest, last point === integrityScore).
   * Powers the hero micro-sparkline so the owner sees the trend behind the number.
   */
  integrityTrend: number[]
  /** Positive/neutral/negative split */
  split: SentimentSplit
  /** Recurring themes with verbatim quotes */
  themes: SentimentTheme[]
  /** Claim accuracy issues */
  claimAccuracy: ClaimAccuracyRow[]
  /** Before/after recovery event */
  recoveryEvent: RecoveryEvent
}

// ---------------------------------------------------------------------------
// Traffic surface (AI Traffic & Crawler Analytics)
// ---------------------------------------------------------------------------

/** A single weekly data point for a specific crawler bot */
export interface CrawlerBotPoint {
  /** ISO date string */
  date: string
  /** Number of crawl hits */
  hits: number
  /** Optional violet agent-event annotation */
  agentEvent?: { label: string } | null
}

/** Weekly crawler trend: per-bot time series */
export interface CrawlerTrend {
  bot: string
  points: CrawlerBotPoint[]
}

/** Per-engine session + conversion attribution */
export interface ReferralAttribution {
  engine: string
  sessions: number
  conversions: number
}

/** A page's crawl + citation performance */
export interface ContentPerformance {
  path: string
  crawlHits: number
  citations: number
}

/** Per-page drill row */
export interface TrafficDrillRow {
  path: string
  pageTitle: string
  crawlHits: number
  citations: number
  aiSessions: number
  conversionRate: number
}

/** Top-level shape for the Traffic surface fixture */
export interface DemoTraffic {
  /** Hero: total AI-referred sessions in last 30 days */
  aiReferredSessions: number
  /** Hero delta vs previous 30 days (+/−) */
  aiReferredDelta: number
  /** Weekly crawler trend per bot */
  crawlerTrend: CrawlerTrend[]
  /** Per-engine referral attribution */
  referralAttribution: ReferralAttribution[]
  /** Top content pages */
  contentPerformance: ContentPerformance[]
  /** Per-page drill rows */
  drill: TrafficDrillRow[]
}

// ---------------------------------------------------------------------------
// Market surface (Market Intelligence & Prompt Volume)
// ---------------------------------------------------------------------------

/** A single prompt/query row in the market intelligence table */
export interface MarketPromptRow {
  id: string
  query: string
  monthlyVolume: number
  region: string
  intent: 'informational' | 'transactional' | 'navigational'
  /** Whether we are currently cited for this query */
  cited: boolean
  /** Whether Beamix is tracking this prompt */
  tracked: boolean
}

/** A trending/emerging prompt to promote */
export interface TrendingPrompt {
  query: string
  weeklyVolumeGrowth: number
  intent: 'informational' | 'transactional' | 'navigational'
}

/** Age band in the demographics breakdown */
export interface AgeBand {
  range: string
  pct: number
}

/** Income band in the demographics breakdown */
export interface IncomeBand {
  range: string
  pct: number
}

/** Audience demographics breakdown */
export interface MarketDemographics {
  ageBands: AgeBand[]
  incomeBands: IncomeBand[]
  genderSplit: { male: number; female: number; other: number }
}

/** Drill data for a single prompt */
export interface MarketPromptDrill {
  promptId: string
  volumeTrend: number[]
  demographics: MarketDemographics
  whoCited: string[]
}

/** Top-level shape for the Market surface fixture */
export interface DemoMarket {
  /** Hero: total addressable prompt volume (monthly) */
  addressableVolume: number
  /** All tracked + untracked prompts */
  prompts: MarketPromptRow[]
  /** Emerging queries to promote */
  trendingPrompts: TrendingPrompt[]
  /** Audience demographics */
  demographics: MarketDemographics
  /** Per-prompt drill data keyed by prompt id */
  drill: Record<string, MarketPromptDrill>
}

// ---------------------------------------------------------------------------
// Ask surface (Ask Beamix copilot)
// ---------------------------------------------------------------------------

/** A citation attached to a copilot message */
export interface AskCitation {
  type: 'scan' | 'prompt' | 'competitor' | 'page'
  label: string
  href: string
}

/** A single message in the copilot thread */
export interface AskMessage {
  id: string
  role: 'user' | 'beamix'
  content: string
  citations?: AskCitation[]
}

/** A step in the grounding ledger */
export interface GroundingStep {
  label: string
  /** e.g. "Read 3 scans · 18 prompts" */
  detail: string
}

/** Top-level shape for the Ask surface fixture */
export interface DemoAsk {
  /** Suggested starter questions */
  suggestedQuestions: string[]
  /** A sample conversation thread */
  thread: AskMessage[]
  /** The grounding ledger steps the agent ran */
  groundingSteps: GroundingStep[]
}

// ---------------------------------------------------------------------------
// Builder surface (Workflow / Agent Builder)
// ---------------------------------------------------------------------------

/** A workflow template */
export interface WorkflowTemplate {
  id: string
  name: string
  description: string
  nodeCount: number
}

/** A node in a workflow graph */
export interface WorkflowNode {
  id: string
  type: 'plan' | 'research' | 'do' | 'qa' | 'summarize'
  label: string
  config: Record<string, string | number | boolean>
}

/** An edge between two workflow nodes */
export interface WorkflowEdge {
  from: string
  to: string
}

/** A workflow graph */
export interface Workflow {
  name: string
  nodes: WorkflowNode[]
  edges: WorkflowEdge[]
}

/** A step in a dry-run preview */
export interface DryRunStep {
  label: string
  status: 'done' | 'running' | 'pending'
  /** e.g. "3 pages queued" or "$0.04" */
  figure: string
}

/** A saved workflow entry */
export interface SavedWorkflow {
  name: string
  lastRun: string | null
  schedule: string | null
}

/** Top-level shape for the Builder surface fixture */
export interface DemoBuilder {
  /** Available workflow templates */
  templates: WorkflowTemplate[]
  /** A sample workflow graph */
  workflow: Workflow
  /** Dry-run preview */
  dryRun: { steps: DryRunStep[]; estCost: string }
  /** User's saved workflows */
  savedWorkflows: SavedWorkflow[]
}

// ---------------------------------------------------------------------------
// Reports surface (Reports & Exports)
// ---------------------------------------------------------------------------

/** A block that can be added to a report */
export interface ReportBlock {
  id: string
  label: string
  /** 'user' = always available; 'agent' = agent-generated / gated */
  kind: 'user' | 'agent'
}

/** A saved report */
export interface SavedReport {
  id: string
  name: string
  blockCount: number
  lastSaved: string
  shareUrl: string | null
}

/** An active report being built */
export interface ActiveReport {
  title: string
  blocks: string[]
}

/** An export connector */
export interface ReportConnector {
  name: string
  gated: boolean
}

/** Top-level shape for the Reports surface fixture */
export interface DemoReports {
  blockCatalog: ReportBlock[]
  savedReports: SavedReport[]
  activeReport: ActiveReport
  connectors: ReportConnector[]
}

// ---------------------------------------------------------------------------
// Team surface (Team & Roles)
// ---------------------------------------------------------------------------

/** A team member row */
export interface TeamMember {
  id: string
  name: string
  email: string
  role: 'Owner' | 'Admin' | 'Analyst' | 'Viewer'
  lastActive: string
  avatarUrl: string | null
}

/** A pending invite row */
export interface PendingInvite {
  email: string
  role: 'Admin' | 'Analyst' | 'Viewer'
  sentAt: string
}

/** Seat usage */
export interface SeatUsage {
  used: number
  total: number
}

/** Top-level shape for the Team surface fixture */
export interface DemoTeam {
  members: TeamMember[]
  pendingInvites: PendingInvite[]
  seats: SeatUsage
  ssoEnabled: boolean
  auditLogGated: boolean
}

// ---------------------------------------------------------------------------
// Agency surface (Agency / Pitch Workspace)
// ---------------------------------------------------------------------------

/** A finding in a prospect audit */
export interface AuditFinding {
  label: string
  severity: 'critical' | 'warning' | 'info'
  detail: string
}

/** A generated prospect audit */
export interface ProspectAudit {
  prospectDomain: string
  score: number
  headline: string
  findings: AuditFinding[]
  generatedAt: string
}

/** A step in the dry-run audit pipeline ledger */
export interface AgencyDryRunStep {
  label: string
  detail: string
}

/** A client roster entry */
export interface AgencyClient {
  name: string
  domain: string
  status: 'active' | 'pitching' | 'lead'
}

/** White-label config per client */
export interface WhiteLabelConfig {
  clientId: string
  logoUrl: string | null
  accent: string
  customDomain: string | null
}

/** A lead in the agency pipeline */
export interface AgencyLead {
  prospect: string
  stage: 'audit' | 'pitch' | 'client'
}

/** Top-level shape for the Agency surface fixture */
export interface DemoAgency {
  sampleAudit: ProspectAudit
  dryRunSteps: AgencyDryRunStep[]
  clients: AgencyClient[]
  whiteLabel: WhiteLabelConfig[]
  leads: AgencyLead[]
}

// ---------------------------------------------------------------------------
// Shopping surface (Shopping / Ecommerce — Bright Smile Dental shop)
// ---------------------------------------------------------------------------

/** Per-attribute accuracy check for a SKU */
export interface AttributeCheck {
  correct: boolean
  claimedValue: string
  actualValue: string
  claimId?: string
  /** href to the fix agent if incorrect */
  correctHref?: string
}

/** Attribute matrix for a SKU */
export interface AttributeMatrix {
  price: AttributeCheck
  specs: AttributeCheck
  availability: AttributeCheck
}

/** Shopper sentiment for a SKU */
export interface SkuSentiment {
  positive: number
  neutral: number
  negative: number
}

/** A SKU in the shopping surface */
export interface ShoppingSku {
  id: string
  name: string
  aiVisibility: number
  position: number
  aiRevenue: number
  attributeMatrix: AttributeMatrix
  shopperSentiment: SkuSentiment
}

/** A per-SKU drill detail row */
export interface ShoppingDrillRow {
  skuId: string
  engine: string
  queriesTested: string[]
  positionTrend: number[]
  topCitedCompetitor: string | null
}

/** Top-level shape for the Shopping surface fixture */
export interface DemoShopping {
  /** Hero: AI-attributed revenue (ILS) */
  aiAttributedRevenue: number
  /** Hero: AI shopping visibility % */
  aiShoppingVisibility: number
  skus: ShoppingSku[]
  drill: ShoppingDrillRow[]
}
