import { ProductNav } from '@/components/shared/product-nav'
import { ProductFooter } from '@/components/shared/product-footer'
import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | Beamix',
  description: 'Beamix terms of service and usage agreement.',
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using Beamix ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These terms apply to all users, including free scan users, trial users, and paying subscribers.`,
  },
  {
    title: '2. Description of Service',
    content: `Beamix provides AI search visibility monitoring, analysis, and optimization tools for businesses. The Service includes AI-powered scanning of search engines, content generation via AI agents, competitor analysis, and related features. Results are generated using third-party AI models and are provided as recommendations, not guarantees of performance.`,
  },
  {
    title: '3. Account Registration',
    content: `To access dashboard features, you must create an account with a valid email address. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years old to create an account. You agree to provide accurate and complete information during registration.`,
  },
  {
    title: '4. Free Scans and Trial',
    content: `Free scans are limited to 3 per IP address per 24-hour period. Free scan results are available for 30 days. The 7-day trial period begins on your first dashboard visit after account creation and includes limited agent credits. Trial features may differ from paid plan features.`,
  },
  {
    title: '5. Subscription and Billing',
    content: `Paid subscriptions are billed through Paddle, our payment processor. Prices are listed on our pricing page and may change with 30 days notice. Subscriptions auto-renew unless cancelled. You may cancel at any time through your billing settings. Refunds are handled per Paddle's refund policy. Unused agent credits expire at the end of each billing period, with up to 20% rollover.`,
  },
  {
    title: '6. Acceptable Use',
    content: `You agree not to: (a) use the Service for any illegal purpose; (b) attempt to reverse-engineer, scrape, or extract data from the Service beyond normal use; (c) share account credentials with unauthorized parties; (d) use AI-generated content in ways that violate third-party AI provider terms; (e) submit false business information; (f) attempt to circumvent rate limits or usage restrictions.`,
  },
  {
    title: '7. Intellectual Property',
    content: `Content generated by Beamix AI agents is provided for your business use. You retain ownership of your business data and any content you create or modify. Beamix retains ownership of the platform, algorithms, and underlying technology. You grant Beamix a limited license to process your data as needed to provide the Service.`,
  },
  {
    title: '8. Data and Privacy',
    content: `Your use of the Service is also governed by our Privacy Policy. We collect and process data as described therein. Business data you provide (website URLs, business names, queries) is used to deliver scan results and recommendations.`,
  },
  {
    title: '9. AI-Generated Content Disclaimer',
    content: `Content and recommendations generated by Beamix AI agents are produced using third-party AI models (including but not limited to OpenAI, Anthropic, Google, and Perplexity). Outputs may contain inaccuracies. You are responsible for reviewing and verifying all AI-generated content before publishing or acting on it. Beamix does not guarantee specific visibility improvements or search engine rankings.`,
  },
  {
    title: '10. Service Availability',
    content: `We aim to maintain high availability but do not guarantee uninterrupted service. We may perform maintenance, updates, or modifications that temporarily affect availability. We will make reasonable efforts to notify users of planned downtime.`,
  },
  {
    title: '11. Limitation of Liability',
    content: `To the maximum extent permitted by law, Beamix shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.`,
  },
  {
    title: '12. Termination',
    content: `We may suspend or terminate your account if you violate these terms. You may delete your account at any time through Settings. Upon termination, your data will be deleted within 30 days, except as required by law or our data retention policies.`,
  },
  {
    title: '13. Changes to Terms',
    content: `We may update these terms from time to time. Material changes will be communicated via email or in-app notification at least 30 days before taking effect. Continued use after changes constitutes acceptance.`,
  },
  {
    title: '14. Governing Law',
    content: `These terms are governed by the laws of the State of Israel. Any disputes shall be resolved in the courts of Tel Aviv-Jaffa, Israel.`,
  },
  {
    title: '15. Contact',
    content: `For questions about these terms, contact us at legal@beamix.app.`,
  },
]

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <ProductNav />

      <main className="flex-1 px-6 pb-16 pt-12">
        <div className="mx-auto max-w-3xl">
          <h1 className="font-sans font-medium text-3xl text-foreground mb-2">
            Terms of Service
          </h1>
          <p className="text-muted-foreground text-sm mb-10">Last updated: March 2026</p>

          <div className="space-y-8">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="font-sans font-semibold text-lg text-foreground mb-2">
                  {section.title}
                </h2>
                <p className="text-muted-foreground leading-relaxed">{section.content}</p>
              </section>
            ))}
          </div>

          <div className="mt-12 flex items-center gap-4 text-sm text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">
              Privacy Policy
            </Link>
          </div>
        </div>
      </main>

      <ProductFooter />
    </div>
  )
}
